name: flutter_devs
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^2.4.0
  cupertino_icons: ^0.1.2
  provider: ^2.0.1+1
  cloud_firestore: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.5.0
  json_serializable: ^3.0.0

flutter:
  uses-material-design: true
